### ISSUE TITLE
Documentation of Gumstix Raspberry Pi Zero Battery Board Demo

### ISSUE THREAD

**Issue by jdimpson** [gumstix/demo-src#5]
Hello.

How does  the gumstix raspbian image differ from the standard raspbian image of the same date? The one referenced in https://github.com/gumstix/demo-src/tree/master/gumstix_raspberry_pi_zero_battery_board_demo

And what does the bmi160-i2c.dtbo overlay do?

My concern is to understand whats required to use the battery board.

Thank you!

**Comment by michael-gumstix** [comment]
The main difference is that the kernel has been updated to include the driver for the BMI-160 sensor - the demo won't work without this driver included. 

The overlay is needed for the driver to be properly loaded. 

Let me know if you have any further questions!

**Comment by jdimpson** [comment]
Thanks! What driver are you using? I've found this one: [https://github.com/BoschSensortec/BMI160_driver](https://github.com/BoschSensortec/BMI160_driver)
